### ISSUE TITLE
Does not build today - duplicate definition

### ISSUE THREAD

**Issue by quicklisp** [gregcman/sucle#26]
I get this fatal build warning today:

```
; caught WARNING:
;   Duplicate definition for 5FUN found in one file.
;   See also:
;     The ANSI Standard, Section 3.2.2.3
```

**Comment by gmasching** [comment]
This commit: https://github.com/gmasching/sucle/commit/70837ab74070dc1197aec0145c064a66e768ee5b

Comments out the other definitions of `5fun`, but it also adds other code as well.
So this particular error should be fixed, but the other new code may not build.

**Comment by quicklisp** [comment]
This remains an issue: http://report.quicklisp.org/2020-01-16/failure-report/sucle.html#sucle

**Comment by gmasching** [comment]
This commit https://github.com/gmasching/sucle/commit/d3201d46898a53297e9e9c40695acb691b75c49f should fix the problem. It adds an `eval-when` around the variables and also comments out duplicate functions.
