### ISSUE TITLE
Trying to quickload sucle

### ISSUE THREAD

**Issue by thrashdin** [gregcman/sucle#30]
```
COMPILE-FILE-ERROR while
compiling #<CL-SOURCE-FILE "window" "glfw3">
   [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]
```

**Comment by gmasching** [comment]
The latest version is not likely in quicklisp, but hopefully will be soon. See: https://github.com/gmasching/sucle/issues/26

Also, are there any other error messages?

**Comment by thrashdin** [comment]
No, nothing else.
