### ISSUE TITLE
OpenGL 2.1

### ISSUE THREAD

**Issue by handicraftsman** [gregcman/sucle#8]
Any plans on supporting PCs with OpenGL 2.1? Aforementioned Minecraft supports it and its widespread across old PCs like mine.

**Comment by terminal625** [comment]
Does it run on your machine? It should run on GLSL 100+ and any OpenGL with display list support, which im pretty sure 2.1 does. As for future support/plans, I want to support the oldest GL version possible by keeping things simple, just plain old display lists and vertex arrays.

**Comment by handicraftsman** [comment]
Okay, i will try that in few dayz (cannot use my pc atm).

**Comment by gmasching** [comment]
OpenGL 2.1 is being depreciated for OpenGL 3

**Comment by handicraftsman** [comment]
You should look into googles Angle - it supports mapping opengl es 2.0 calls to all popular graphics apis, even to metal or webgl. OpenGL ES 3.0 (supported too) doesnt work on webgl, directx 9 and similar old api versions though. Was writing this issue because my pc did not support opengln 3+.

**Comment by gmasching** [comment]
Google Angle looks useful, just writing OpenGL ES and having it work anywhere. However, I do not currently have the resources in order to try it out at the moment. 

As for supporting 2.1 and 3.0, it should be simple enough to support display lists and vertex arrays.

**Comment by handicraftsman** [comment]
Yeah, i understand the resources problem - i have a teapot instead of a proper computer 😄.

**Comment by gmasching** [comment]
Sucle currently renders to either a 2.1 display lists or 3.* vertex buffers, meaning that 2.1 should be supported now.
